# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(1322, 1090)
        self.centralwidget = QtWidgets.QWidget(HomePage)
        self.centralwidget.setObjectName("centralwidget")
        self.kullanici_bilgileri = QtWidgets.QLabel(self.centralwidget)
        self.kullanici_bilgileri.setGeometry(QtCore.QRect(20, 20, 1121, 34))
        self.kullanici_bilgileri.setObjectName("kullanici_bilgileri")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 160, 1291, 771))
        self.tabWidget.setObjectName("tabWidget")
        self.homepage_tab = QtWidgets.QWidget()
        self.homepage_tab.setObjectName("homepage_tab")
        self.subscribe = QtWidgets.QPushButton(self.homepage_tab)
        self.subscribe.setGeometry(QtCore.QRect(1130, 130, 151, 44))
        self.subscribe.setObjectName("subscribe")
        self.users = QtWidgets.QLabel(self.homepage_tab)
        self.users.setGeometry(QtCore.QRect(660, 20, 181, 34))
        self.users.setObjectName("users")
        self.login = QtWidgets.QPushButton(self.homepage_tab)
        self.login.setGeometry(QtCore.QRect(1130, 70, 151, 44))
        self.login.setObjectName("login")
        self.blogger_list = QtWidgets.QComboBox(self.homepage_tab)
        self.blogger_list.setGeometry(QtCore.QRect(840, 10, 441, 44))
        self.blogger_list.setObjectName("blogger_list")
        self.request_list = QtWidgets.QPushButton(self.homepage_tab)
        self.request_list.setGeometry(QtCore.QRect(1130, 190, 151, 44))
        self.request_list.setObjectName("request_list")
        self.new_blog = QtWidgets.QPushButton(self.homepage_tab)
        self.new_blog.setGeometry(QtCore.QRect(1130, 660, 151, 44))
        self.new_blog.setObjectName("new_blog")
        self.block = QtWidgets.QPushButton(self.homepage_tab)
        self.block.setGeometry(QtCore.QRect(1130, 250, 151, 44))
        self.block.setObjectName("block")
        self.listWidget = QtWidgets.QListWidget(self.homepage_tab)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 631, 691))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.listWidget.setPalette(palette)
        self.listWidget.setObjectName("listWidget")
        self.tabWidget.addTab(self.homepage_tab, "")
        self.message_tab = QtWidgets.QWidget()
        self.message_tab.setObjectName("message_tab")
        self.messages_widget = QtWidgets.QWidget(self.message_tab)
        self.messages_widget.setGeometry(QtCore.QRect(10, 70, 1261, 631))
        self.messages_widget.setObjectName("messages_widget")
        self.kullanici_bilgileri_2 = QtWidgets.QLabel(self.message_tab)
        self.kullanici_bilgileri_2.setGeometry(QtCore.QRect(10, 20, 211, 34))
        self.kullanici_bilgileri_2.setObjectName("kullanici_bilgileri_2")
        self.blogger_list_messages = QtWidgets.QComboBox(self.message_tab)
        self.blogger_list_messages.setGeometry(QtCore.QRect(840, 10, 441, 44))
        self.blogger_list_messages.setObjectName("blogger_list_messages")
        self.users_2 = QtWidgets.QLabel(self.message_tab)
        self.users_2.setGeometry(QtCore.QRect(660, 20, 181, 34))
        self.users_2.setObjectName("users_2")
        self.tabWidget.addTab(self.message_tab, "")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(1150, 950, 151, 44))
        self.exit.setObjectName("exit")
        self.id_label = QtWidgets.QLabel(self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(20, 60, 1111, 34))
        self.id_label.setObjectName("id_label")
        self.nickname_label = QtWidgets.QLabel(self.centralwidget)
        self.nickname_label.setGeometry(QtCore.QRect(20, 100, 1121, 34))
        self.nickname_label.setObjectName("nickname_label")
        HomePage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomePage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1322, 42))
        self.menubar.setObjectName("menubar")
        HomePage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomePage)
        self.statusbar.setObjectName("statusbar")
        HomePage.setStatusBar(self.statusbar)

        self.retranslateUi(HomePage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "Uygulama Ekranı"))
        self.kullanici_bilgileri.setText(_translate("HomePage", "Kullanıcı Bilgileri"))
        self.subscribe.setText(_translate("HomePage", "Takip Et"))
        self.users.setText(_translate("HomePage", "Kullanıcılar :"))
        self.login.setText(_translate("HomePage", "Bağlan"))
        self.request_list.setText(_translate("HomePage", "Liste İste"))
        self.new_blog.setText(_translate("HomePage", "Yeni Blog"))
        self.block.setText(_translate("HomePage", "Blokla"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homepage_tab), _translate("HomePage", "Anasayfa"))
        self.kullanici_bilgileri_2.setText(_translate("HomePage", "Direkt Mesajlar"))
        self.users_2.setText(_translate("HomePage", "Kullanıcılar :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.message_tab), _translate("HomePage", "Mesajlar"))
        self.exit.setText(_translate("HomePage", "Çıkış"))
        self.id_label.setText(_translate("HomePage", "ID :"))
        self.nickname_label.setText(_translate("HomePage", "Kullanıcı Adı :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomePage = QtWidgets.QMainWindow()
    ui = Ui_HomePage()
    ui.setupUi(HomePage)
    HomePage.show()
    sys.exit(app.exec_())

